accent = "#dda15e"
cursor = "#e0e0e0"
foreground = "#e0e0e0"
background = "#000000"
selection_foreground = "#000000"
selection_background = "#e0e0e0"

color0 = "#000000"
color1 = "#e2ecbf"
color2 = "#86964f"
color3 = "#e2ecbf"
color4 = "#dda15e"
color5 = "#e2ecbf"
color6 = "#86964f"
color7 = "#e0e0e0"
color8 = "#e2ecbf"
color9 = "#999999"
color10 = "#86964f"
color11 = "#b2b2b2"
color12 = "#dda15e"
color13 = "#e2ecbf"
color14 = "#e2ecbf"
color15 = "#e0e0e0"
